### ISSUE TITLE
UwU

### ISSUE THREAD

**Issue by scidsgn** [Team-G4/base-g4#1]
hiIIi~~~

g4-kun did a foopsie woopsie on noxxy woxxy mode OwO
somwan plzz fixx the fucky wucky in noxxy mode senpay *proceeds to dance like Nicki Minaj in Anaconda*

![Snlzlh1a_400x400](https://user-images.githubusercontent.com/11379882/68598980-0bf36380-04a0-11ea-8649-d6c59e9ba877.jpg)

oWo see you next brexit

**Comment by ghost** [comment]
sci I swear to God
