### ISSUE TITLE
Copy of https://github.com/Team-G4/g4x/issues/16: A bunch of 404s

### ISSUE THREAD

**Issue by justchen1369** [Team-G4/base-g4#3]
Web release
![image](https://user-images.githubusercontent.com/35386456/71021923-4e2a4900-20cd-11ea-8803-51e23309210a.png)
Also, I have a couple changes I'd like to test. Ice Bear, would you test them for me when I get home from school?

**Comment by justchen1369** [comment]
appears to be fixed, magically.

**Comment by ghost** [comment]
Seems fine to me? Are you on https://play.g4game.wtf or...?

![image](https://user-images.githubusercontent.com/30705254/71022316-0f889480-20b5-11ea-9647-e0044d8c0e3f.png)

**Comment by ghost** [comment]
Make sure you're not playing through macOS Safari or iOS, because Apple web standards are whack

**Comment by justchen1369** [comment]
I am not. It's fixed now, anyway. However, it's not loading and cpu is ~30%.

**Comment by ghost** [comment]
> I am not. It's fixed now, anyway. However, it's not loading and cpu is ~30%.

I'll look into what's going on in a bit, this is weird behavior

**Comment by justchen1369** [comment]
it appears that the loading screen was covering up the actual game, and so I was waiting for quite a while before trying deleting the loading screen HTML element, which allowed me to play the game.

**Comment by ghost** [comment]
why am I not surprised

**Comment by justchen1369** [comment]
It was not clear that "Play g4" was a clickable button. 
I feel stupid now :D

**Comment by ghost** [comment]
Oh, that should be obvious, but okay...
