### ISSUE TITLE
what is the use of glslCanvas.js?

### ISSUE THREAD

**Issue by justchen1369** [Team-G4/base-g4#7]

**Comment by dynamyc010** [comment]
it's for something sci was experimenting with

**Comment by scidsgn** [comment]
Support of GLSL shaders, scrapped last minute due to lovely stability

**Comment by justchen1369** [comment]
do we still need this file, and can I remove it?

**Comment by scidsgn** [comment]
I'd leave it there for now

**Comment by justchen1369** [comment]
![image](https://user-images.githubusercontent.com/35386456/71115044-0ecc2d00-219f-11ea-8abe-3193ce10e3ef.png)
... array.prototype.forEach exists

**Comment by scidsgn** [comment]
what even is this, is this from glslCanvas?

**Comment by justchen1369** [comment]
yep

**Comment by scidsgn** [comment]
send complaints to https://github.com/patriciogonzalezvivo/glslCanvas
